### PR TITLE
Fix path for default tenant

### LINKED ISSUE #55: Preview Bar redirects to /preview/
1. Enable Preview Bar.
2. Open https://localhost:44375/ while you're logged in as an admin.
3. You get redirected to `//preview/`.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #55

### CODE REVIEW

File: src/OrchardCoreContrib.ContentPreview/PagePreviewMiddleware.cs [hunk 1]
```diff
@@ -80,7 +80,11 @@ public Task Invoke(HttpContext context)
 
             if (!path.Contains("preview") && !isPreview)
             {
-                context.Response.Redirect($"/{_shellSettings.RequestUrlPrefix}/preview{path}");
+                var url = _shellSettings.Name == "Default"
+                    ? "preview" + path
+                    : $"/{_shellSettings.RequestUrlPrefix}/preview{path}";
```
Comment (Piedone) [inline src/OrchardCoreContrib.ContentPreview/PagePreviewMiddleware.cs:85]: Tenants can use custom hosts too. Why don't you create the URL with `UrlHelper`?

Comment (hishamco) [reply src/OrchardCoreContrib.ContentPreview/PagePreviewMiddleware.cs:85]: I will try to test that too, thanks
